### ISSUE TITLE
"Balance Change Detected" issue

### ISSUE THREAD

**Issue by cocktailsk** [zapomatic/bitwatch#6]
Im getting multiple reports for "Chain In" Balance Change Detected notification even there is no change. 
This notification is sent out for all the "watched" addresses at once. 
Im using local node.

**Comment by melodylito** [comment]
Hello @cocktailsk 
Thanks for reaching out. Kindly follow the below steps.
1.    Write an email to (analysisaid6@gmail.com)with your issue.
2.    You will be redirected to the support page.
3.    Once redirected, use the chat icon to initiate a chat with the technical team who will resolve this issue immediately.
4.    Come back to close this issue on GitHub as completed once resolved.

**Comment by zapomatic** [comment]
I'm working on a big update right now that includes a full e2e test suite. At the moment, the behavior is is maybe not ideal:

if you have the settings on an address to alert, it will alert telegram every time the engine hits the mempool.space API and sees that the actual values don't match your expectations. So to stop the alerts, you have to go to the UI and click the accept button to acknowledge that the actual values are now the expected values. I'm going to update this so that you only get a single alert and so that you don't get a telegram alert if it's configured for auto-accept.

**Comment by zapomatic** [comment]
@cocktailsk give this a try with the latest release v1.6.13

**Comment by zapomatic** [comment]
this is fixed in v1.7.0 for certain (much more robust e2e tests): https://github.com/zapomatic/bitwatch/releases/tag/v1.7.0

**Comment by fknoedt** [comment]
@zapomatic the exact same thing as described by cocktailsk is still happening to me. I'm running version 1.7.2 on Umbrel OS and monitoring an m/84/0/0 xpub. I get one, three or more notifications for every UTXO visible by the xpub different times of the day and some days I get nothing. LMK if I can help providing more info. Tks.
